backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads"
public_folder: "/uploads"

i18n:
  structure: multiple_folders
  locales: [en, es]
  default_locale: en

collections:
  - name: "blog"
    i18n: true
    label: "Blog"
    folder: "src/content/blog"
    create: true
    delete: true
    slug: "{{slug}}-{{year}}"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          i18n: true,
        }
      - {
          label: "Publish Date",
          name: "pubDate",
          widget: "date",
          format: "MMM DD YYYY",
          i18n: duplicate,
        }
      - {
          label: "Featured Image",
          name: "heroImage",
          widget: "image",
          i18n: duplicate,
        }
      - {
          label: "Rating (scale of 1-5)",
          name: "rating",
          widget: "number",
          i18n: duplicate,
        }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
  - name: "snippets"
    label: "Snippets"
    folder: "src/content/snippets"
    create: true
    delete: true
    fields:
      - { label: "Name", name: "Name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Snippet", name: "Snippet", widget: "code" }
